[package]
name = "tensorflowsui"
edition = "2024.beta"
published-at = "0xb460157d7d132a59f7ec1c2f2c5698a377bc8596a9e9acde1de53db13c412858"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/devnet" }

[addresses]
tensorflowsui = "0xb460157d7d132a59f7ec1c2f2c5698a377bc8596a9e9acde1de53db13c412858"
std = "0x1"

[dev-dependencies]

[dev-addresses]


