[package]
name = "Sml"
edition = "2024.beta"
published-at = "0x8d77eaf0b5503337f113fae8878e5a15ce1af0b13ea3e38327d2e280d4fa9679"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/testnet" }

[addresses]
sml = "0x8d77eaf0b5503337f113fae8878e5a15ce1af0b13ea3e38327d2e280d4fa9679"
